default: styles/mastodon_colorides.scss
sediroloc: styles/sediroloc.scss
mastodon: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
macaron: styles/macaron.scss
fairy-floss: styles/fairy-floss.scss
rosaceae: styles/pink.scss
quartzo: styles/light_pink.scss
sunset: styles/sunset.scss
colorwave: styles/colorwave.scss
teal: styles/teal.scss
terminal: styles/terminal.scss
flamingo: styles/flamingo.scss
purple-haze: styles/purple_haze.scss
meemu-purple: styles/meemu-default.scss
meemu-vaporwave: styles/meemu.scss
